<script lang="ts">
	import '../app.css';
	import favicon from '$lib/assets/favicon.svg';

	let { children } = $props();
</script>

<svelte:head>
	<link rel="icon" href={favicon} />
</svelte:head>

{@render children?.()}

<footer class="content-layer py-6 text-center">
	<p class="font-mono text-sm text-[var(--text-secondary)]/60">
		Generated by <a
			href="https://claude.ai/claude-code"
			target="_blank"
			rel="noopener noreferrer"
			class="text-[var(--accent-purple)]/80 transition-colors hover:text-[var(--accent-purple)]"
			>Claude Code</a
		>
	</p>
</footer>
