<div class="content-layer flex h-screen flex-col px-4 pt-16 pb-4">
	<main class="flex flex-1 items-center justify-center">
		<div class="w-full max-w-4xl">
			<slot />
		</div>
	</main>
	<footer class="py-4 text-center">
		<p class="font-mono text-sm text-[var(--text-secondary)]/60">
			Generated by <a
				href="https://claude.ai/code"
				target="_blank"
				rel="noopener noreferrer"
				class="text-[var(--accent-purple)]/80 transition-colors hover:text-[var(--accent-purple)]"
				>Claude Code</a
			>
		</p>
	</footer>
</div>
